import type {Metadata} from "next";
import '../styles/main.scss'
import Navigation from "@/components/Navigation";
import {ReactLenis, useLenis} from 'lenis/react'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <Navigation/>
        <ReactLenis root>
            {children}
        </ReactLenis>
        </body>
        </html>
    );
}
